// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyiitdnfmncjgkpvtfbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5aWl0ZG5mbW5jamdrcHZ0ZmJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNTYzMTQsImV4cCI6MjA2NDczMjMxNH0.4z3Fr23C5cwkuqX0gF5-GIGrd-iA2wNZsYEkt0Cp4O8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);